In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.mean([73,432,53,78,4])

128.0

In [5]:
np.median([73,432,53,78,4])

73.0

In [6]:
np.average([73,432,53,78,4])

128.0

In [7]:
l = [1,2,3,4,5]

In [9]:
d_1 = np.array(l)

In [10]:
d_1

array([1, 2, 3, 4, 5])

In [12]:
d_1.ndim   #direction

1

In [18]:
d_2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [19]:
d_2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [21]:
np.array([[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']])

array([['1', '2', '3', '4', '5'],
       ['10', '20', '30', '40', '50'],
       ['A', 'B', 'C', 'D', 'E']], dtype='<U11')

In [22]:
d_2.ndim

2

In [24]:
d_3 =np.array([[[1,2,3,4,5],[10,20,30,40,50],['A','B','C','D','E']]])

In [26]:
d_3.ndim

3

In [29]:
d_1

array([1, 2, 3, 4, 5])

In [28]:
d_1[0]

1

In [30]:
np.random.randint(10,20,5)

array([16, 14, 15, 13, 14])

In [31]:
np.random.randint(1,5,10)

array([2, 2, 4, 2, 2, 2, 4, 4, 1, 2])

In [32]:
np.random.random(50)

array([0.34118711, 0.37976008, 0.43019546, 0.60158399, 0.3991546 ,
       0.51980688, 0.4696491 , 0.3128164 , 0.10069854, 0.65868684,
       0.20010809, 0.02176239, 0.73203867, 0.9709919 , 0.82712931,
       0.42194226, 0.48067541, 0.50843045, 0.18628871, 0.43710632,
       0.1920637 , 0.21274389, 0.09741239, 0.93768693, 0.02873767,
       0.8635109 , 0.19714578, 0.73550001, 0.2097775 , 0.28562235,
       0.66196573, 0.78240726, 0.05606049, 0.39600189, 0.93284356,
       0.51798637, 0.89885714, 0.55290526, 0.72284159, 0.69172386,
       0.99834389, 0.190862  , 0.42335317, 0.85240581, 0.97729043,
       0.72632946, 0.39339994, 0.63089077, 0.0751229 , 0.55148626])

In [33]:
np.random.rand(1,3)

array([[0.97399022, 0.46996546, 0.94003428]])

In [34]:
np.random.rand(3,3)

array([[0.58907494, 0.65389318, 0.55179289],
       [0.66515833, 0.09034062, 0.26966586],
       [0.31203641, 0.46791619, 0.09650868]])